### ISSUE TITLE
Third-party API calls（타사 API 호출）

### ISSUE THREAD

**Issue by Sndeok** [Taewan-P/gpt_mobile#12]
Hello developers! If I want to use other third-party APIs to replace the official OpenAI call address, where should I change it in your project?
안녕하세요 개발자 여러분! 다른 타사 API를 사용하여 공식 OpenAI 호출 주소를 대체하려면 프로젝트의 어디에서 변경해야 합니까?

**Comment by Taewan-P** [comment]
Hi,
To replace the official OpenAI call address, you should look at [`app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt#L48`](https://github.com/Taewan-P/gpt_mobile/blob/bcacd2fb2eae3bf01f0cbcf9206d7d75983907a1/app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt#L48). 

Note that this projects uses [unofficial OpenAI library written in Kotlin](https://github.com/aallam/openai-kotlin) for OpenAI API calls. For raw api calls, check out how Anthropic APIs are called in the same file since I implemented it.

**Comment by Sndeok** [comment]
> 你好， 要替换官方 OpenAI 调用地址，你应该看看[`app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt#L48`](https://github.com/Taewan-P/gpt_mobile/blob/bcacd2fb2eae3bf01f0cbcf9206d7d75983907a1/app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt#L48)。
> 
> 请注意，该项目使用[非官方的 OpenAI 库（以 Kotlin 编写）](https://github.com/aallam/openai-kotlin)进行 OpenAI API 调用。对于原始 API 调用，请查看自我实现以来，Anthropic API 是如何在同一文件中调用的。

Thank you for your reply! I checked the code you pointed out, but I didn't find the specific replacement API address. Are you calling the OpenAI official API address through https://api.openai.com?

**Comment by Taewan-P** [comment]
> but I didn't find the specific replacement API address.

See what is initialized in L50, then look at this code. Initialize a OpenAIHost, then set its baseUrl with your API. 

[`openai-kotlin/openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt#L36`](https://github.com/aallam/openai-kotlin/blob/9c30cfb713e3cebc5de262230c5646546680e084/openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt#L36)

```kotlin
openAI = OpenAI(platform.token ?: "", host = OpenAIHost(baseUrl = "https://..."))
```

By default, it uses `OpenAIHost.OpenAI`, which is a companion object declared in [`OpenAIConfig#L100`](https://github.com/aallam/openai-kotlin/blob/9c30cfb713e3cebc5de262230c5646546680e084/openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt#L100), so yes it is an official API address.
