### ISSUE TITLE
free models

### ISSUE THREAD

**Issue by rainerZugang** [Taewan-P/gpt_mobile#25]
Hi,

i really love your APP, where I can ASK different LLMs at once. But I need for all of this a paid API in my country...but i want it for free, because it is quite expensive to have 3 LLM paid APIs

Can you also add free models with direct access? And can you add free account for Gemini, chatgpt,..?

Thanks a lot!

**Comment by Taewan-P** [comment]
Hello,
Thank you for your interest.

Unfortunately, this app is **intended** to use paid APIs since using paid APIs are still **way more cheaper** than subscribing to each premium versions. (ChatGPT plus: $20/month, Claude pro: $20/month, Gemini Advanced: $19.99/month)

I use three APIs right now, but I get less than $5/month in total. Depending on my usage it gets lower since I only pay for what I asked.

If that is expensive, you should create your own Ollama server and serve the model that you want to use... and wait for Ollama support (which is work in progress right now)

Currently, I do not have plans adding direct free model access since it requires reverse engineering, which will just be a cycle of blocking & breaking between the devs & platforms.
